version: "3.8"
services:
  nodejs:
    entrypoint: .docker/entrypoint.sh
    build:
      context: .
      dockerfile: ./api/Dockerfile
    ports:
      - 8000:8000
    environment:
      - DATABASE_URL=file:./dev.db
    volumes:
      - ./api:/api
    image: "nodejs"
    container_name: api-todolist
    networks:
      vpcbr:
        ipv4_address: 10.5.0.5
  web:
    entrypoint: .docker/entrypoint.sh
    build:
      context: .
      dockerfile: ./web/Dockerfile
    ports:
      - 5173:5173
    volumes:
      - ./web:/web
      - /web/node_modules
    image: "nodejs-web"
    container_name: web-todolist
    networks:
      vpcbr:
        ipv4_address: 10.5.0.6
  app:
    entrypoint: .docker/entrypoint.sh
    build:
      context: .
      dockerfile: ./app/Dockerfile
    ports:
      - 8081:8081
      - 19001:19001
      - 19002:19002
    volumes:
      - ./app:/app
      - /app/node_modules
    image: "nodejs-app"
    container_name: app-todolist
    networks:
      vpcbr:
        ipv4_address: 10.5.0.7
networks:
  vpcbr:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16
          gateway: 10.5.0.1
